language: go
sudo: false
go:
  - 1.11.x
services:
  - docker
install:
  - export GO111MODULE=on
  - go get github.com/mattn/goveralls
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $GOPATH/bin v1.12.3
before_script:
  - GO111MODULE=on golangci-lint run --disable megacheck
script:
  - export GO111MODULE=on
  - if [[ "$TRAVIS_GO_VERSION" == 1.11.* ]]; then /bin/bash ./.scripts/cover.sh; else go test -v -race -tags integration ./...; fi
