shutdown_timeout: 10 #time to let sequencer finish running sequences
var: # var will not be parsed, its just to consolidate variables for manifest
  slack_token: &slack_token ""
  slack_verification_token: &slack_verification_token ""
  slack_bot_icon: &slack_bot_icon ":gun:"
  github_webhook_secret: &github_webhook_secret ""
  github_oauth2_token: &github_oauth2_token ""